development:
  adapter: mysql2
  encoding: utf8
  database: gallery_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: gallery_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: gallery_prod
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
