# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: true
:concurrency: 5
:queues:
  - [high, 7]
  - [alb_mailer, 5]
